Fevol/obsidian-typings

.gitignore
package-lock.json
package.json

Add missing package.json

---

obsidian-ex.d.ts

Use proper typings

---

obsidian-ex.d.ts
package-lock.json
package.json

Fix compilation

---

package.json

Follow @types convention for automatic discover

---

README.md
package.json

Use publishable package name

---

obsidian-ex.d.ts

Add missing `Plugin.enable()`, `Plugin.disable()` functions

Add Plugin enable/disable

---

obsidian-ex.d.ts

Addressed concerns mentioned in #16

Move definition to InternalPlugin

---

obsidian-ex.d.ts
package-lock.json
package.json
tsconfig.json

Add more definitions

---

obsidian-ex.d.ts

Replace lambdas with functions

---

obsidian-ex.d.ts

Add file explorer typings

---

dummy.ts
obsidian-ex.d.ts

Add explanation of the purpose of `dummy.ts`

---

README.md
obsidian-ex.d.ts
package-lock.json
package.json
tsconfig.json

Fix more lambdas

---

obsidian-ex.d.ts

fix: app.metadataTypeManager.setType/unsetType are async

---

obsidian-ex.d.ts

Change return type of loadLocalStorage from string to any
Fixes #48

[FIX] loadLocalStorage return type 

---

src/obsidian/augmentations/FileManager.d.ts
src/obsidian/augmentations/Platform.d.ts
src/obsidian/augmentations/Setting.d.ts
src/obsidian/internals/HotkeysSettingTab.d.ts
src/obsidian/internals/LinkUpdate.d.ts
src/obsidian/types.d.ts

Link updaters

---

src/implementations/createTFile.ts
src/implementations/createTFolder.ts
src/implementations/index.ts

Add createTFile/TFolder functions

---

src/implementations/createTFile.ts
src/implementations/createTFolder.ts
src/implementations/index.ts
src/obsidian/augmentations/App.d.ts

Fix return type of saveAttachment

---

package-lock.json
package.json
src/implementations/createTFile.ts
src/implementations/createTFolder.ts
src/implementations/index.ts
src/obsidian/augmentations/App.d.ts
src/obsidian/augmentations/WorkspaceLeaf.d.ts
src/obsidian/augmentations/WorkspaceSplit.d.ts

Import attachments

---

package-lock.json
package.json
src/obsidian/augmentations/App.d.ts
src/obsidian/augmentations/Vault.d.ts
src/obsidian/augmentations/WorkspaceLeaf.d.ts
src/obsidian/augmentations/WorkspaceSplit.d.ts

Get available path for attachments

---

src/obsidian/augmentations/App.d.ts
src/obsidian/augmentations/Vault.d.ts
src/obsidian/internals/DragManager.d.ts
src/obsidian/types.d.ts

Drag manager

---

package.json

Use proper dependency versions

---

src/obsidian/internals/InternalPlugins/Graph/GraphEngine.d.ts
src/obsidian/internals/InternalPlugins/Graph/GraphLink.d.ts
src/obsidian/internals/InternalPlugins/Graph/GraphNode.d.ts
src/obsidian/internals/InternalPlugins/Graph/GraphOptions.d.ts
src/obsidian/internals/InternalPlugins/Graph/GraphPluginInstance.d.ts
src/obsidian/internals/InternalPlugins/Graph/GraphPluginInstanceOptions.d.ts
src/obsidian/internals/InternalPlugins/Graph/GraphRenderer.d.ts

Hi,
It's Kapirklaa from the OMG Discord.
I did my best to find the correct typings for the Graph plugin, its renderer, its engine, and basically anything I needed to add while I was developing my plugin.
Your guide to contribute was really helpful, thanks a lot.
Let me know if I need to change anything! I'm not sure I did everything correctly...
Thanks for all the amazing work.

Add typings for the graph plugin

---

src/obsidian/internals/InternalPlugins/Graph/GraphRenderer.d.ts

I added three new properties to the GraphRenderer class, since I needed them in my plugin.

Add initGraphics, destroyGraphics and iframeEl to GraphRenderer

---

src/obsidian/internals/InternalPlugins/FileExplorer/AbstractFileTreeItem.d.ts
src/obsidian/internals/InternalPlugins/FileExplorer/FileExplorerView.d.ts
src/obsidian/internals/InternalPlugins/FileExplorer/FileExplorerViewFileItemsRecord.d.ts
src/obsidian/internals/InternalPlugins/FileExplorer/FileExplorerViewSortOrder.d.ts
src/obsidian/internals/InternalPlugins/FileExplorer/FileTreeItem.d.ts
src/obsidian/internals/InternalPlugins/FileExplorer/FileTreeItemParent.d.ts
src/obsidian/internals/InternalPlugins/FileExplorer/FolderTreeItem.d.ts
src/obsidian/internals/Tree/ContainerTreeItem.d.ts
src/obsidian/internals/Tree/Tree.d.ts
src/obsidian/internals/Tree/TreeItem.d.ts
src/obsidian/internals/Tree/TreeNode.d.ts
src/obsidian/internals/Tree/TreeNodeVChildren.d.ts
src/obsidian/internals/Tree/TreeRoot.d.ts

I added and refactor some of Tree and FileExplorerView types.

Made some improvements to Tree and FileExplorerView

---

src/obsidian/internals/MetadataTypeManager/MetadataTypeManager.d.ts

Sorry the commit message looks weird, I didn't realize it would silently strip anything in backticks

Updated `MetadataTypeManager.getTypeInfo()`
